"""
Utilities for identifying test data.

Test data is generated by automated E2E tests and should be filterable
in admin dashboards to show only real user data by default.
"""

# Email domains used by automated testing frameworks
TEST_EMAIL_DOMAINS = [
    "inbox.testmail.app",  # Used by E2E happy path tests
]


def is_test_email(email: str) -> bool:
    """
    Check if an email address belongs to automated test data.

    Args:
        email: Email address to check

    Returns:
        True if the email matches a test email domain pattern
    """
    if not email:
        return False
    email_lower = email.lower()
    return any(email_lower.endswith(f"@{domain}") for domain in TEST_EMAIL_DOMAINS)
